### PR TITLE
#23 (+ #24, #35, #36) - Toolbar configuration + refinements + bugs

### PR DESCRIPTION
**Pull request by fredevery**

### CODE REVIEW

**Comment by fredevery** [comment]
@LevKanter I haven't managed to reproduce the issue locally. I did notice another issue (#38) that I am hoping is the reason for the issue you're seeing. Could you pull and retry?

If you still experience the issue could you give me full steps to repro? Please try list everything, it might be caused by a series of things.

**Comment by LevKanter** [comment]
@fredevery thanks - I am still reproducing that issue after pulling/rebuilding/retrying.

The steps I'm taking are as follows:
- After `yarn build` and `yarn local_server`, load the page http://localhost:4848/
- Tripple click on the third paragraph to select it and bring up the toolbar:
image
- Toggle any of the block-level formatters (toggling 'bold' and 'italics' doesn't cause any problems). For example, toggle 'h1':
image
The error fires before it looks like any content markup is changed.

**Comment by LevKanter** [comment]
@fredevery just curious, can you clarify what the `no-open-tag` and `no-close-tag` tags that have been added to the preview consoles are for?

**Comment by fredevery** [comment]
@LevKanter As mentioned the blockquote range bug has a fix in the PR for issue 9.

The `no-open-tag`/`no-close-tag` tags are there as a visual debug aid, in case, for any reason tag pairs go awry.

**Pull request merged**
